name: test build on ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: run build
        run: mkdir build && cd build && cmake .. && make -j$(nproc)